"""
Emits the Foundation as CSS custom properties.

The trick that makes the architecture work in CSS: a custom property resolves
lazily, at the point of use. So the semantics are declared once per theme, and
everything that points to them - including the composite focus ring - is
declared ONCE, on :root, and follows the theme switch by itself.

Run: python3 css.py     (writes build/foundation/al-foundation.css)
"""
import json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, '..', '..', 'tools'))
from paths import TOKENS_JSON, FOUNDATION_CSS, out, rel  # noqa: E402

# Reads the tokens.json generated by export.py and writes to build/foundation/. No chdir: a
# path anchored on the file gives the same result from any folder.
T = json.load(open(TOKENS_JSON))

OUT = out(FOUNDATION_CSS)
L = []
w = L.append


def block(title):
    w('')
    w(f'  /* {title} */')


w('/* AL Design System - Foundation')
w(f' * v{T["meta"]["version"]} - {T["meta"]["license"]}')
w(' * GENERATED by src/foundation/css.py. Do not edit by hand: run the script.')
w(' */')
w('')
w(':root {')
w('  color-scheme: light dark;')

# ---------------- primitives ----------------
block('color primitives - the raw ramp. Do not consume directly in a component.')
for fam, steps in T['color']['primitive'].items():
    for step, hexv in steps.items():
        w(f'  --al-color-{fam}-{step}: {hexv};')

# ---------------- semantics (light) ----------------
block('color semantics - LIGHT THEME. This is where the theme is resolved.')
for name, pair in T['color']['semantic'].items():
    if pair is None:
        continue
    w(f'  --al-{name}: {pair[0]};')

# ---------------- typography ----------------
block('typography')
w(f'  --al-font-sans: {T["type"]["family"]["sans"]};')
w(f'  --al-font-mono: {T["type"]["family"]["mono"]};')
for k, v in T['type']['weight'].items():
    w(f'  --al-font-weight-{k}: {v};')
for k, v in T['type']['size'].items():
    w(f'  --al-font-size-{k}: {v}px;')
for k, v in T['type']['leading'].items():
    w(f'  --al-line-height-{k}: {v}px;')

# ---------------- space, radius, border ----------------
block('spacing')
for k, v in T['space'].items():
    w(f'  --al-space-{k}: {v}px;')

block('radius')
for k, v in T['radius'].items():
    w(f'  --al-radius-{k}: {v}px;')

block('border')
for k, v in T['border']['width'].items():
    w(f'  --al-border-width-{k}: {v}px;')
w(f'  --al-border-focus-offset: {T["border"]["focusOffset"]}px;')

block('icon size - each step is named by its own value. The Icon component\n'
      '     has no fixed scale: this names the recurring sizes.')
for k, v in T['iconSize'].items():
    w(f'  --al-icon-size-{k}: {v}px;')

# ---------------- motion ----------------
block('motion - duration by the SIZE of what moves (feedback, the rest, by role),\n'
      '     curve by the TYPE of action. Enter decelerates (ease-out), exit accelerates (ease-in).')
for k, v in T['motion']['duration'].items():
    w(f'  --al-motion-duration-{k}: {v}ms;')
for k, v in T['motion']['easing'].items():
    w(f'  --al-motion-easing-{k}: cubic-bezier({", ".join(str(n) for n in v)});')

# ---------------- elevation ----------------
block('elevation - LIGHT THEME')
for k, v in T['elevation'].items():
    if k.startswith('_'):
        continue
    w(f'  --al-elevation-{k}: {v["light"]};')

# ---------------- focus ring ----------------
block('focus ring - composed once, follows the theme by itself.\n     Two layers: a gap in the background color, then the ring in the focus color.')
ring_total = 'calc(var(--al-border-focus-offset) + var(--al-border-width-focus))'
for kind, tok in (('default', 'shadow-focus-default'), ('error', 'shadow-focus-error')):
    w(f'  --al-focus-ring-{kind}:')
    w(f'    0 0 0 var(--al-border-focus-offset) var(--al-bg-canvas),')
    w(f'    0 0 0 {ring_total} var(--al-{tok});')
w('}')


# ---------------- dark theme ----------------
def dark_body(indent):
    out = []
    for name, pair in T['color']['semantic'].items():
        if pair is None:
            continue
        out.append(f'{indent}--al-{name}: {pair[1]};')
    for k, v in T['elevation'].items():
        if k.startswith('_'):
            continue
        out.append(f'{indent}--al-elevation-{k}: {v["dark"]};')
    return out


w('')
w('/* DARK THEME. Three states, not two: with no stamp on the root, only')
w(' * prefers-color-scheme decides; with a stamp, the explicit choice wins. */')
w('@media (prefers-color-scheme: dark) {')
w('  :root:not([data-theme="light"]) {')
L.extend(dark_body('    '))
w('  }')
w('}')
w('')
w(':root[data-theme="dark"] {')
w('  color-scheme: dark;')
L.extend(dark_body('  '))
w('}')
w('')
w('/* The stamp also tells the BROWSER. `color-scheme: light dark` on :root')
w(' * lets the native UI - the Textarea grip and scrollbar, the Select list -')
w(' * follow the system; with a forced theme, it would follow the system and')
w(' * not the page. With no stamp it is not needed: system and page agree. */')
w(':root[data-theme="light"] {')
w('  color-scheme: light;')
w('}')
w('')

open(OUT, 'w').write('\n'.join(L))

n_prim = sum(len(v) for v in T['color']['primitive'].values())
n_sem = sum(1 for v in T['color']['semantic'].values() if v is not None)
print(f'{rel(OUT)} written')
print(f'  color primitives  : {n_prim}')
print(f'  color semantics   : {n_sem} x 2 themes')
print(f'  icon sizes        : {len(T["iconSize"])}')
print(f'  motion            : {len(T["motion"]["duration"])} durations, {len(T["motion"]["easing"])} curves')
print(f'  focus rings       : 2 (composite, resolve by themselves per theme)')
print(f'  bytes             : {os.path.getsize(OUT)}')
