"""
Token layer for the Icon.

Same one rule as the Button's layer: nothing here invents a value. Every Icon
token points to a Foundation token by NAME, and the gate at the end of the file
rejects anything that is a loose value.

Naming:
  code  -> icon-ink-on-brand      (hyphen)
  Figma -> icon/ink               (folder, collection `3. Icon ink`)
They are different layers. Never collapse one into the other.

Two decisions in this layer that the diff doesn't explain on its own:

1. The BOX is called `icon-box`, not `icon-size`. `--al-icon-size-16` already
   exists and is the Foundation primitive; if the component token had the same
   name, it would point to itself and the custom property would die in a cycle.
   `box` is the role in the component, `size` is the step on the scale.

2. The INK has four tokens because the `3. Icon ink` collection in Figma has
   four modes. But the CSS default is none of them: it is `currentColor`. The
   modes exist in Figma because Figma has no `currentColor` - inside the
   Button, the icon needs SOMEONE to say what color it is. On the web the icon
   inherits the label's color by itself, and one keyword replaces the whole
   collection. These four tokens are the EXPLICIT output, for an icon that
   lives outside an actionable element and has nothing to inherit from.

Run: python3 tokens.py     (writes al-icon-tokens.css, don't redirect stdout)
"""
import json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, '..', '..', '..', 'tools'))
from paths import FOUNDATION_SRC, TOKENS_JSON, comp_out  # noqa: E402
sys.path.insert(0, FOUNDATION_SRC)

from palette import SEM                     # noqa: E402
from tokenlib import resolve_foundation, css_ref, save_css  # noqa: E402

FOUND = json.load(open(TOKENS_JSON))   # noqa: E402


# ------------------------------------------------------------------- box
# The four recurring steps. They are not a ceiling: `--al-icon-box` is public
# and accepts any value at the point of use. The component is outlined on the
# 24 grid and works at any size - these four only name what repeats.
BOX = {
  '16': 'iconSize.16',
  '20': 'iconSize.20',
  '24': 'iconSize.24',
  '32': 'iconSize.32',
}

# ------------------------------------------------------------------- ink
# One line per mode of the `3. Icon ink` collection. Same order as Figma.
INK = {
  'default':  'text-primary',
  'on-brand': 'text-on-brand',
  'on-solid': 'text-on-solid',
  'disabled': 'text-disabled',
}

# The component's default step. It lives here and not in the CSS so that
# changing the default is one token line, not a stylesheet edit.
DEFAULT_BOX = '24'


# ------------------------------------------------------------------ gate
def run():
    alias, resolved, problems = {}, {}, []

    for step, ref in BOX.items():
        name = f'icon-box-{step}'
        alias[name] = ref
        try:
            resolved[name] = resolve_foundation(ref)
        except (KeyError, TypeError):
            problems.append(f'{name}: {ref} does not exist in the Foundation')

    for mode, ref in INK.items():
        name = f'icon-ink-{mode}'
        alias[name] = ref
        if ref.startswith('#'):
            problems.append(f'{name}: loose hex ({ref}) - every color is born as an alias of a semantic')
            continue
        if ref not in SEM:
            problems.append(f'{name}: points to {ref}, which does not exist in the semantic layer')
            continue
        light, dark = SEM[ref]
        resolved[name] = {'light': light, 'dark': dark}

    if DEFAULT_BOX not in BOX:
        problems.append(f'default step {DEFAULT_BOX} does not exist in BOX')

    print('=' * 70)
    print('ICON TOKEN LAYER')
    print('=' * 70)
    for name in sorted(alias):
        print(f'  {name:<24} -> {alias[name]}')
    print('-' * 70)
    print(f'default step: {DEFAULT_BOX}px  (the rest is a modifier or a value at the point of use)')
    print('pending: none')
    print('-' * 70)

    if problems:
        print(f'{len(problems)} TOKEN(S) FAIL THE ALIAS GATE:')
        for p in problems:
            print('   ', p)
        return 1

    print(f'{len(alias)} tokens: {len(alias)} aliases of the Foundation, 0 loose values.')
    write_css(alias)
    write_json(alias, resolved)
    return 0


def write_css(alias):
    L = []
    w = L.append
    w('/* AL Design System - Icon tokens')
    w(' * GENERATED by src/components/icon/tokens.py. Do not edit by hand.')
    w(' *')
    w(' * There is no theme block here: each ink points to a semantic, and the')
    w(' * theme switches on :root - the same element where these aliases are')
    w(' * declared. So :root re-substitutes all of them at once.')
    w(' */')
    w('')
    w(':root {')
    w('')
    w('  /* box - a recurring step, not a ceiling */')
    for step in BOX:
        w(f'  --al-icon-box-{step}: {css_ref(BOX[step])};')
    w('')
    w('  /* ink - explicit output. The component default is currentColor. */')
    for mode in INK:
        w(f'  --al-icon-ink-{mode}: {css_ref(INK[mode])};')
    w('}')
    w('')

    save_css('icon', '\n'.join(L))


def write_json(alias, resolved):
    out = {
        'meta': {
            'component': 'Icon',
            'version': '0.1.0',
            'foundation': FOUND['meta']['version'],
            'figmaNode': '127:341',
            'family': 'lucide',
            'grid': 24,
            'strokeWidth': 2,
            'boxes': list(BOX),
            'inks': list(INK),
            'note': 'The component\'s default color is none of the icon-ink-*: it is '
                    'currentColor. The four tokens are the explicit output.',
        },
        'defaultBox': DEFAULT_BOX,
        'alias': alias,
        'resolved': resolved,
        'pending': {},
    }
    path = comp_out('icon', 'tokens.json')
    json.dump(out, open(path, 'w'), indent=2, ensure_ascii=False)
    print('build/components/icon/tokens.json written')


if __name__ == '__main__':
    sys.exit(run())
